import * as github from '@actions/github';
import { IssueMode } from '../config/inputs';
import { logger } from '../util/logger';

interface IssuePublishOptions {
  token: string;
  title: string;
  body: string;
  label?: string;
  mode: IssueMode;
}

async function ensureLabel(
  octokit: ReturnType<typeof github.getOctokit>,
  owner: string,
  repo: string,
  label?: string
): Promise<string | undefined> {
  if (!label) return undefined;
  try {
    await octokit.rest.issues.getLabel({ owner, repo, name: label });
    return label;
  } catch (err) {
    try {
      await octokit.rest.issues.createLabel({
        owner,
        repo,
        name: label,
        color: '0e8a16',
        description: 'Generated by gha-mutability-check'
      });
      return label;
    } catch (innerErr) {
      logger.warn(`Could not create label ${label}: ${innerErr}`);
      return undefined;
    }
  }
}

export async function publishIssue(options: IssuePublishOptions): Promise<number> {
  const { token, title, body, label, mode } = options;
  const octokit = github.getOctokit(token);
  const { owner, repo } = github.context.repo;

  const labelToUse = await ensureLabel(octokit, owner, repo, label);
  const labels = labelToUse ? [labelToUse] : undefined;

  if (mode === 'update') {
    logger.info('Issue update mode is not implemented yet; creating a new issue instead.');
  }

  const response = await octokit.rest.issues.create({
    owner,
    repo,
    title,
    body,
    labels
  });

  return response.data.number;
}
